version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - NODE_ENV=development
      - npm run build 
artifacts:
  files:
    - '**/*'
  name: $(date+%Y%m%d%H%M%S)-$CODEBUILD_BUILD_NUMBER
